// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _webApiKey = 'AIzaSyAFPmbGYzuFhropyLDn3iidaRlzgVX_hpo';

  static const String _iosApiKey = 'AIzaSyD1__BEaD8G3vETuOcGgvR6pc3zq8jBnu8';

  static const String _macosApiKey = 'AIzaSyD1__BEaD8G3vETuOcGgvR6pc3zq8jBnu8';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.android:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'This app supports only web and Apple platforms (iOS/macOS).',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:478876596230:web:bf478c1b7775f737dd6b87',
    messagingSenderId: '478876596230',
    projectId: 'insaat-yonetim-takip',
    authDomain: 'insaat-yonetim-takip.firebaseapp.com',
    storageBucket: 'insaat-yonetim-takip.firebasestorage.app',
    measurementId: 'G-DVZPKCE7PM',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _iosApiKey,
    appId: '1:478876596230:ios:b9a10331363d2749dd6b87',
    messagingSenderId: '478876596230',
    projectId: 'insaat-yonetim-takip',
    storageBucket: 'insaat-yonetim-takip.firebasestorage.app',
    iosBundleId: 'com.lento.app',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _macosApiKey,
    appId: '1:478876596230:ios:b9a10331363d2749dd6b87',
    messagingSenderId: '478876596230',
    projectId: 'insaat-yonetim-takip',
    storageBucket: 'insaat-yonetim-takip.firebasestorage.app',
    iosBundleId: 'com.lento.app',
  );

}