// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.android:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'This app supports only web and Apple platforms (iOS/macOS).',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQgEJnuvmuUJurB_4V6vQUmJdAcMiulvQ',
    appId: '1:478876596230:web:bf478c1b7775f737dd6b87',
    messagingSenderId: '478876596230',
    projectId: 'insaat-yonetim-takip',
    authDomain: 'insaat-yonetim-takip.firebaseapp.com',
    storageBucket: 'insaat-yonetim-takip.firebasestorage.app',
    measurementId: 'G-DVZPKCE7PM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB7cuL_7TWha6f4FU80Mem6TqpDkMfxf4',
    appId: '1:478876596230:ios:b9a10331363d2749dd6b87',
    messagingSenderId: '478876596230',
    projectId: 'insaat-yonetim-takip',
    storageBucket: 'insaat-yonetim-takip.firebasestorage.app',
    iosBundleId: 'com.example.insaatYonetim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB7cuL_7TWha6f4FU80Mem6TqpDkMfxf4',
    appId: '1:478876596230:ios:b9a10331363d2749dd6b87',
    messagingSenderId: '478876596230',
    projectId: 'insaat-yonetim-takip',
    storageBucket: 'insaat-yonetim-takip.firebasestorage.app',
    iosBundleId: 'com.example.insaatYonetim',
  );

}