// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _webApiKey = String.fromEnvironment(
    'FIREBASE_WEB_API_KEY',
    defaultValue: 'REPLACE_WITH_ROTATED_WEB_API_KEY',
  );

  static const String _iosApiKey = String.fromEnvironment(
    'FIREBASE_IOS_API_KEY',
    defaultValue: 'REPLACE_WITH_ROTATED_IOS_API_KEY',
  );

  static const String _macosApiKey = String.fromEnvironment(
    'FIREBASE_MACOS_API_KEY',
    defaultValue: 'REPLACE_WITH_ROTATED_MACOS_API_KEY',
  );

  static String _resolveApiKey(String envName, String value) {
    if (value.isEmpty || value.startsWith('REPLACE_WITH_ROTATED_')) {
      throw UnsupportedError(
        'Missing Firebase API key for $envName. Update firebase_keys.local.json and run with --dart-define-from-file.',
      );
    }

    if (!value.startsWith('AIza')) {
      throw UnsupportedError(
        'Invalid Firebase API key format for $envName. Check rotated key value in firebase_keys.local.json.',
      );
    }

    return value;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.android:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'This app supports only web and Apple platforms (iOS/macOS).',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _resolveApiKey('FIREBASE_WEB_API_KEY', _webApiKey),
    appId: '1:478876596230:web:bf478c1b7775f737dd6b87',
    messagingSenderId: '478876596230',
    projectId: 'insaat-yonetim-takip',
    authDomain: 'insaat-yonetim-takip.firebaseapp.com',
    storageBucket: 'insaat-yonetim-takip.firebasestorage.app',
    measurementId: 'G-DVZPKCE7PM',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _resolveApiKey('FIREBASE_IOS_API_KEY', _iosApiKey),
    appId: '1:478876596230:ios:b9a10331363d2749dd6b87',
    messagingSenderId: '478876596230',
    projectId: 'insaat-yonetim-takip',
    storageBucket: 'insaat-yonetim-takip.firebasestorage.app',
    iosBundleId: 'com.lento.app',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _resolveApiKey('FIREBASE_MACOS_API_KEY', _macosApiKey),
    appId: '1:478876596230:ios:b9a10331363d2749dd6b87',
    messagingSenderId: '478876596230',
    projectId: 'insaat-yonetim-takip',
    storageBucket: 'insaat-yonetim-takip.firebasestorage.app',
    iosBundleId: 'com.lento.app',
  );

}